modlix-india/nocode-ui

ui-app/client/src/components/Buttonbar/ButtonBar.tsx, ui-app/client/src/components/Buttonbar/ButtonBarStyle.tsx, ui-app/client/src/components/Buttonbar/buttonBarStyleProperties.ts, ui-app/client/src/components/Buttonbar/buttonBarproperties.ts
=> Added buttonBar component

ui-app/client/src/components/PageEditor/editors/propertyValueEditors/ImageEditor.tsx
by adding authorisation token for both delete and upload request methods.
=> Updated imageEditor.tsx

ui-app/client/src/components/Grid/Grid.tsx, ui-app/client/src/context/ParentExtractor.ts, ui-app/client/src/context/StoreContext.ts, ui-app/client/src/functions/SetStore.ts
On Hover event and parent store for tables changes
=> NCLC-301 On Hover event changes for grid and parent store changes

ui-app/client/src/components/Dropdown/Dropdown.tsx
Updated changes when search label is empty in dropdown component.
=> Updated when filter when label is empty

ui-app/client/src/components/FileUpload/FileUpload.tsx
updated fileupload component processing for different csv file when uploaded in the component
=> updated filetype processing for csv file

ui-app/client/src/Engine/RenderEngineContainer.tsx, ui-app/client/src/components/FillerDefinitionEditor/components/EditorBody.tsx, ui-app/client/src/components/FillerDefinitionEditor/components/TextBox.tsx, ui-app/client/src/components/FillerDefinitionEditor/components/fillerCommons.ts, ui-app/client/src/components/FillerValueEditor/FillerValueEditor.tsx, ui-app/client/src/components/FillerValueEditor/FillerValueEditorStyle.tsx, ui-app/client/src/components/FillerValueEditor/components/Editor.tsx, ui-app/client/src/components/FillerValueEditor/components/FontPicker.tsx, ui-app/client/src/components/FillerValueEditor/components/ImageEditor.tsx, ui-app/client/src/components/FillerValueEditor/components/ImagePoup.tsx, ui-app/client/src/components/FillerValueEditor/components/MapChoice.tsx, ui-app/client/src/components/FillerValueEditor/components/ObjectPopup.tsx, ui-app/client/src/components/FillerValueEditor/components/Palette.tsx, ui-app/client/src/components/FillerValueEditor/components/Popup.tsx, ui-app/client/src/components/FillerValueEditor/components/fillerCommons.ts, ui-app/client/src/components/HelperComponent.tsx
1. Changed the color of the dotted highlight to Blue.
2. Along with the list of grid keys to scroll to, added an option to choose where the scrolled component should be.
3. Close icon added for the popups and image popup.
4. Added Map editor for adding map and image.
5. Page refresh when there is no scroll grid is specified.
6. Re arrangement of the gallery images in the array is done.
=> Added enhancements

ui-app/client/src/components/PageEditor/functions/PageOperations.ts
allowChildrenTobeAdded, it was for the child component but we need the allow children for parent component.
=> Removed the allowChildrenTobeAdded

ui-app/client/src/components/SchemaBuilder/SchemaBuilderStyle.tsx
Issues with the schema editor json popup is fixed along with the server function properties changes.
=> Properties of KIRun editor in the server functions has issues

ui-app/client/src/components/TextBox/TextBox.tsx, ui-app/client/src/components/TextBox/textBoxProperties.ts
Added a feature to show commas and dots for number formatting based on the system settings and on the fixed locale setting too.
=> Added formatting for textbox for numbers

ui-app/client/src/components/Image/Image.tsx, ui-app/client/src/components/Image/imageProperties.ts
Added image lazy loading attribute in the Image component
=> Image loading attribute

ui-app/client/src/components/Tabs/Tabs.tsx
changed the tabs active styles
=> changed tabs  active styles

ui-app/client/src/components/PhoneNumber/PhoneNumberStyle.tsx, ui-app/client/src/components/PhoneNumber/components/Dropdown.tsx
adjusted the position of dropdownBody from fixed position to absolute…position and changed the expression for calculating the top, left, right position values based on the position of parent element position inside the body to avoid dropdownBody missalignment during the scrolling of the page
=> Changed the dropDownBody styles

ui-app/client/src/components/Button/buttonProperties.ts, ui-app/client/src/components/Grid/Grid.tsx, ui-app/client/src/components/Grid/gridProperties.ts, ui-app/client/src/components/Image/Image.tsx, ui-app/client/src/components/Image/imageProperties.ts
Need to add similar on click stop propagations to other on clicks.
=> Added stop propagation to not propagate the clicks to the containers.

ui-app/client/src/components/PageEditor/editors/stylePropertyValueEditors/simpleEditors/Dropdown.tsx
changed onclick event to onMouseDown event to ensure the dropdown functionality
=> changed onClick event to onMouseDown

ui-app/client/src/components/Video/Video.tsx
Added a key prop to update video source when binding path is added
=> Added a key

ui-app/client/package-lock.json, ui-app/client/package.json
=> kirun js version updated with latest

ui-app/client/src/functions/ScrollTo.ts, ui-app/client/src/functions/ScrollToGrid.ts, ui-app/client/src/functions/all.ts
Added ui-engine Scroll to function and scrollToGrid functions
=> added ui-engine scroll functions

ui-app/client/src/components/PhoneNumber/PhoneNumber.tsx, ui-app/client/src/components/PhoneNumber/components/Dropdown.tsx, ui-app/client/src/components/TextBox/TextBox.tsx
added the setvalues when the text is empty and changed the regex and added the readonly for phonenumber.
=> fixed the emptyValue handling

ui-app/client/src/functions/Login.ts
Added Otp and Pin parameter to the Login Ui function
=> Feature/Added Otp and Pin parameter to the Login Ui function

ui-app/client/src/components/Calendar/components/CalendarMap.tsx
and the issue for multiple months is resolved in browsemonths, and updated it
=> Updated the logic for months

ui-app/client/src/components/PhoneNumber/PhoneNumber.tsx
If the value is set to empty, it was setting the default value for country code, resolved that issue.
=> Changed the logic for empty string in phonenumber value

ui-app/client/src/components/TableComponents/TableColumnHeader/TableColumnHeader.tsx
added styleproperties for sortIcon as per the subhelpers
=> styles for sortIcon

ui-app/client/src/components/TableComponents/Table/Table.tsx, ui-app/client/src/components/TableComponents/Table/tableProperties.ts, ui-app/client/src/components/TableComponents/TableColumnHeader/TableColumnHeader.tsx, ui-app/client/src/components/TableComponents/TableColumns/tableColumnsProperties.ts
This pull request introduces enhancements to the table component to support customizable sorting logic. Key changes include:
- **New properties**: Added `sortObjectType`, `ascValue`, and `descValue` to enable flexible sorting configurations.
- **Refactored sorting logic**: Improved handling for multiple data formats, ensuring better adaptability.
- **Backward compatibility**: Removed the obsolete `sortKey` property while ensuring backward compatibility through updates.
=> Add support for customizable sorting logic in tables

ui-app/client/dist/css/App.css, ui-app/client/src/App/appStyleProperties.ts
Define new style properties for the validation message container, including alignment, spacing, and visual appearance. Add flexbox styling to improve layout and allow customization of key design elements like padding, border, and background.
=> Update validation message styles and properties

ui-app/client/src/App/appStyleProperties.ts
=> removed val background

ui-app/client/src/commonComponents/FileBrowser/LazyFileBrowser.tsx, ui-app/client/src/components/FormStorageEditor/LazyFormStorageEditor.tsx, ui-app/client/src/components/FormStorageEditor/components/FormEditor.tsx, ui-app/client/src/components/FormStorageEditor/components/formPreviewGeneration.ts, ui-app/client/src/components/FormStorageEditor/formStorageEditorProperties.ts, ui-app/client/src/components/Iframe/Iframe.tsx, ui-app/client/src/components/Image/Image.tsx
This pull request includes multiple updates to improve the functionality and security of application components:
- **Iframe Component**: Enhanced support for secured source URLs by introducing logic to fetch and secure the sources with appropriate headers before rendering.
- **Image Handling**: Simplified and improved secure image URL processing by utilizing `useState` and `useEffect`. This ensures asynchronous handling and avoids direct DOM manipulation.
- **FormStorageEditor**: Added a read-only mode to prevent data modification when necessary, alongside general code cleanup.
- **Image Validation**: Refactored property validation logic to remove unused type parameters and simplify dependencies.
- **General Enhancements**: Addressed minor bugs, such as correcting a typo (`deleteButton`), …
=> Enhance and secure content rendering across components

ui-app/client/dist/styleProperties/Calendar.json, ui-app/client/src/components/Calendar/LazyCalendar.tsx, ui-app/client/src/components/Calendar/calendarProperties.ts, ui-app/client/src/components/Dropdown/dropdownProperties.ts, ui-app/client/src/components/PageEditor/LazyPageEditor.tsx, ui-app/client/src/components/PageEditor/editors/DnDEditor/DnDEditor.tsx, ui-app/client/src/components/PageEditor/editors/DnDEditor/DnDTopBar.tsx, ui-app/client/src/components/PageEditor/pageEditorProperties.ts
This pull request includes the following updates:
- **Page Editor:** Added a new "On Saved Versions" event property to enhance version management functionality. Updated the logic, callbacks, and UI elements related to saved versions.
- **Dropdown Component:** Updated the label text from "No Float Label" to "Do not float Label" for improved clarity and user comprehension.
- **Calendar Component:** Revised property names and descriptions. Introduced a support text field and added shadow and support text styling across various states for enhanced customization.
=> Add support for new events and UI improvements

ui-app/client/src/components/Dropdown/Dropdown.tsx
- Replaced the previous method of moving selected options to the top with a more efficient sorting mechanism using `useMemo`.
- Updated the import statements for better readability.
- Enhanced the dropdown options handling to maintain performance and clarity.
=> Refactor Dropdown component to improve sorting logic

ui-app/client/dist/styleProperties/TextBox.json
Added text box label font for different designs and added text box border for different designs
=> Added textBox Label property

ui-app/client/dist/styleProperties/PhoneNumber.json
This commit includes  padding and width styles for input and dropdown
=> Added Phone Number input box  Padding and drop down width styles

ui-app/client/dist/styleProperties/Dropdown.json, ui-app/client/dist/styleProperties/TextArea.json, ui-app/client/dist/styleProperties/TextBox.json
-> Added Text Area Label font and Text Area Label margin properties for different designs.
-> Added Dropdown Label font, Dropdown box shadow property and Dropdown Label margin properties for different designs.
-> Added Text Box Label margin property.
=> Feature/cx 628 added text area, text box and dropdown label font  and margin properties

ui-app/client/dist/styleProperties/Dropdown.json
dropdown height property is added for different designs
=> Added dropdown height property for different designs

ui-app/client/dist/styleProperties/Otp.json
Added the box shadows for four states default, hasvalue, active, error.
=>  Otp Box shadow properties for four states added.

ui-app/client/dist/styleProperties/Calendar.json, ui-app/client/dist/styleProperties/PhoneNumber.json
Added Calendar Label Margin Property for different designs and Added PhoneNumber Label Margin Property for different designs.
=> Added Label Margin Property For both Calendar and PhoneNumber

ui-app/client/dist/styleProperties/Calendar.json
Added Calendar font properties for Calendar header and Calendar Body for different designs also fixes the bug in Calendar Month Date where display name is same for both padding and border-radius properties.
=> Added Calendar font properties

ui-app/client/dist/styleProperties/TableColumnHeader.json, ui-app/client/dist/styleProperties/TableColumns.json
Now borders of table columns can be added seperately. Height, Width of header can be adjusted.
=> Added the borders, width, height properties.

ui-app/client/dist/styleProperties/Stepper.json, ui-app/client/src/components/Stepper/Stepper.tsx
For horizontal stepper that requires styling for the lines. Currently, we have only one selector, _line that's why i included additional selectors: _active ,_activebeforeline, _done and margin theme styles i have added for list item and step
=> Added styles for the horizontal stepper line and updated margin properties for list items and steps

ui-app/client/src/components/Text/TextStyleProperties.ts
changed the classname for padding and margin in text theme
=> changed the classname for padding and margin

ui-app/client/src/components/ArrayRepeater/ArrayRepeater.tsx, ui-app/client/src/components/ArrayRepeater/arrayRepeaterProperties.ts, ui-app/client/src/components/Grid/gridProperties.ts, ui-app/client/src/context/ParentExtractor.ts
Fixed issue with Parent.Parent.__index bug
=> Added minimize rendering property for the array repeater.

ui-app/client/src/App/App.tsx
Moved the calls to processFontPacks and processIconPacks to a more logical position within the App function, ensuring they are executed before checking properties. This change enhances code readability and maintains the intended functionality without altering the overall behavior.
=> Refactor App component to streamline font and icon pack processing

ui-app/client/src/components/FileUpload/FileUpload.tsx, ui-app/client/src/components/FileUpload/FileUploadStyles.tsx, ui-app/client/src/components/FileUpload/fileUploadProperties.ts, ui-app/client/src/components/Iframe/iframeProperties.ts
added label, supporting text, and mandatory asterisk
Introduce new properties for the FileUpload component to display a label, supporting text, and a mandatory asterisk. Enhance the component's styling to accommodate these additions and improve user experience by providing clearer instructions and visual cues.
Also added `COMMON_COMPONENT_PROPERTIES.visibility` to the properties definition of iframe to enhance maintainability and consistency across components.
=> Nclc2 191 feature label support text for file upload

ui-app/client/dist/styleProperties/PhoneNumber.json, ui-app/client/src/components/PhoneNumber/PhoneNumber.tsx, ui-app/client/src/components/PhoneNumber/phoneNumberProperties.ts
added dailcode binding and store with dail code property and box-shadow for the success validation.
=> added dailcode binding

ui-app/client/src/functions/Logout.ts
- Added 'ssoLogout' parameter to the Logout function signature for improved logout handling.
- Updated API request URL to include the 'ssoLogout' query parameter based on the provided argument.
=> Enhance Logout function to support SSO logout parameter

ui-app/client/dist/styleProperties/Calendar.json, ui-app/client/src/components/Calendar/CalendarStyle.tsx, ui-app/client/src/components/Calendar/LazyCalendar.tsx, ui-app/client/src/components/Calendar/calendarProperties.ts
- Introduced new properties for edit request, confirm, and cancel icons to improve user interaction during editing.
- Updated Calendar styles to display control buttons on hover and in edit mode, enhancing usability.
- Added new style properties for hover backgrounds and other visual states to improve overall design consistency.
- Refactored event handling to streamline the edit mode experience and ensure immediate updates based on user actions.
=> Enhance Calendar component with edit request functionality

ui-app/client/src/components/TextArea/TextArea.tsx
- Updated onEditRequest logic to prevent state change if edit mode is active, enhancing user experience during editing.
- Simplified condition checks for better clarity and maintainability in event handling.
=> Refactor TextArea component to improve edit request handling

ui-app/client/src/components/FileSelector/FileSelector.tsx, ui-app/client/src/components/FileSelector/fileSelectorProperties.ts
1) Fixed a bug where the path state was not updating when startLocation changed. 
2) Added label property.
=> Added label property to FileSelector and fixed start location path upate bug

ui-app/client/src/components/util/getHref.ts
- Added a condition to check if linkPath starts with 'data:', allowing the function to handle data URIs in addition to existing URL formats.
=> Enhance getHref function to support data URIs
